sudo: false
language: python
# cache package wheels (1 cache per python version)
cache: pip
python:
  # TODO: Bump to 3.7 when travis supports that
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox
  - make upload_to_pypi
